<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CustomerBookingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customer_bookings')->insert([
            [
                'booking_id' => 1,
                'customer_name' => 'Chidinma Eze',
                'customer_phone' => '+2348012223344',
                'pickup_location' => 'Ikeja GRA, Lagos',
                'dropoff_location' => 'Murtala Muhammed Airport',
                'pickup_time' => Carbon::now()->addDays(1)->setTime(9, 30),
                'vehicle_category' => 'sedan',
                'booking_source' => 'website',
                'assigned_vehicle' => 1,
                'assigned_driver' => 1,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 2,
                'customer_name' => 'Femi Adeyemi',
                'customer_phone' => '+2348091112233',
                'pickup_location' => 'Lekki Phase 1',
                'dropoff_location' => 'Eko Hotel & Suites',
                'pickup_time' => Carbon::now()->addDays(2)->setTime(14, 0),
                'vehicle_category' => 'van',
                'booking_source' => 'phone',
                'assigned_vehicle' => 3,
                'assigned_driver' => 3,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 3,
                'customer_name' => 'Grace Ojo',
                'customer_phone' => '+2348073334455',
                'pickup_location' => 'Wuse 2, Abuja',
                'dropoff_location' => 'Asokoro, Abuja',
                'pickup_time' => Carbon::now()->addDays(3)->setTime(11, 15),
                'vehicle_category' => 'sedan',
                'booking_source' => 'app',
                'assigned_vehicle' => 2,
                'assigned_driver' => 2,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 4,
                'customer_name' => 'Samuel Okon',
                'customer_phone' => '+2348056667788',
                'pickup_location' => 'Surulere, Lagos',
                'dropoff_location' => 'Victoria Island, Lagos',
                'pickup_time' => Carbon::now()->addDays(4)->setTime(8, 0),
                'vehicle_category' => 'sedan',
                'booking_source' => 'website',
                'assigned_vehicle' => null,
                'assigned_driver' => null,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 5,
                'customer_name' => 'Oluwatobi James',
                'customer_phone' => '+2348061234545',
                'pickup_location' => 'Garki, Abuja',
                'dropoff_location' => 'Jabi Lake Mall',
                'pickup_time' => Carbon::now()->addDays(5)->setTime(10, 45),
                'vehicle_category' => 'luxury',
                'booking_source' => 'app',
                'assigned_vehicle' => 7,
                'assigned_driver' => 7,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 6,
                'customer_name' => 'Adaeze Nwankwo',
                'customer_phone' => '+2348019988776',
                'pickup_location' => 'New GRA, Port Harcourt',
                'dropoff_location' => 'Rumuola, Port Harcourt',
                'pickup_time' => Carbon::now()->addDays(6)->setTime(13, 20),
                'vehicle_category' => 'sedan',
                'booking_source' => 'website',
                'assigned_vehicle' => 5,
                'assigned_driver' => 5,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 7,
                'customer_name' => 'Musa Garba',
                'customer_phone' => '+2348095566770',
                'pickup_location' => 'Zaria Rd, Kano',
                'dropoff_location' => 'Airport Rd, Kano',
                'pickup_time' => Carbon::now()->addDays(7)->setTime(7, 30),
                'vehicle_category' => 'sedan',
                'booking_source' => 'phone',
                'assigned_vehicle' => 4,
                'assigned_driver' => 4,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 8,
                'customer_name' => 'Efe Okoro',
                'customer_phone' => '+2348071122334',
                'pickup_location' => 'Airport Rd, Warri',
                'dropoff_location' => 'Enerhen, Warri',
                'pickup_time' => Carbon::now()->addDays(8)->setTime(16, 10),
                'vehicle_category' => 'van',
                'booking_source' => 'website',
                'assigned_vehicle' => 8,
                'assigned_driver' => 8,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 9,
                'customer_name' => 'Chisom Ude',
                'customer_phone' => '+2348054433221',
                'pickup_location' => 'Ogbunike, Onitsha',
                'dropoff_location' => 'Main Market, Onitsha',
                'pickup_time' => Carbon::now()->addDays(9)->setTime(12, 5),
                'vehicle_category' => 'van',
                'booking_source' => 'app',
                'assigned_vehicle' => 9,
                'assigned_driver' => 9,
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'booking_id' => 10,
                'customer_name' => 'Yetunde Ajayi',
                'customer_phone' => '+2348031100990',
                'pickup_location' => 'Ring Rd, Ibadan',
                'dropoff_location' => 'Samonda, Ibadan',
                'pickup_time' => Carbon::now()->addDays(10)->setTime(18, 45),
                'vehicle_category' => 'sedan',
                'booking_source' => 'website',
                'assigned_vehicle' => 10,
                'assigned_driver' => 10,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
