<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DriversSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('drivers')->insert([
            [
                'driver_id' => 1,
                'supplier_id' => 1,
                'vehicle_id' => 1,
                'driver_name' => 'Ifeanyi Okeke',
                'phone_number' => '+2348031112233',
                'license_number' => 'LIC-AX1021',
                'years_experience' => 8,
                'languages' => 'English, Yoruba, Igbo',
                'professional_experience' => 'Corporate shuttle and executive transport for 5+ years.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 2,
                'supplier_id' => 2,
                'vehicle_id' => 2,
                'driver_name' => 'Usman Abdullahi',
                'phone_number' => '+2348074448899',
                'license_number' => 'LIC-BX2045',
                'years_experience' => 7,
                'languages' => 'English, Hausa',
                'professional_experience' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 3,
                'supplier_id' => 3,
                'vehicle_id' => 3,
                'driver_name' => 'Amaka Nwosu',
                'phone_number' => '+2348025556677',
                'license_number' => 'LIC-CZ3099',
                'years_experience' => 6,
                'languages' => 'English, Yoruba',
                'professional_experience' => 'Airport transfers and tour routes within Lagos.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 4,
                'supplier_id' => 4,
                'vehicle_id' => 4,
                'driver_name' => 'Khadija Sani',
                'phone_number' => '+2348062227744',
                'license_number' => 'LIC-DM4412',
                'years_experience' => 5,
                'languages' => 'English, Hausa',
                'professional_experience' => 'City shuttle operations and corporate client support.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 5,
                'supplier_id' => 5,
                'vehicle_id' => 5,
                'driver_name' => 'Bamidele Ayo',
                'phone_number' => '+2348019098833',
                'license_number' => 'LIC-EH5531',
                'years_experience' => 9,
                'languages' => 'English, Yoruba',
                'professional_experience' => 'Corporate routes and offshore transfers.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 6,
                'supplier_id' => 6,
                'vehicle_id' => 6,
                'driver_name' => 'Chukwudi Eze',
                'phone_number' => '+2348081115544',
                'license_number' => 'LIC-FJ6640',
                'years_experience' => 4,
                'languages' => 'English, Igbo',
                'professional_experience' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 7,
                'supplier_id' => 7,
                'vehicle_id' => 7,
                'driver_name' => 'Zainab Adamu',
                'phone_number' => '+2348092221133',
                'license_number' => 'LIC-GK7755',
                'years_experience' => 10,
                'languages' => 'English, Hausa',
                'professional_experience' => 'Executive chauffeur for VIP clients.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 8,
                'supplier_id' => 8,
                'vehicle_id' => 8,
                'driver_name' => 'Kelvin Okorie',
                'phone_number' => '+2348054477711',
                'license_number' => 'LIC-HL8829',
                'years_experience' => 5,
                'languages' => 'English, Pidgin',
                'professional_experience' => 'Intercity transfers and event shuttles.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 9,
                'supplier_id' => 9,
                'vehicle_id' => 9,
                'driver_name' => 'Ngozi Ekwueme',
                'phone_number' => '+2348079900011',
                'license_number' => 'LIC-JN9932',
                'years_experience' => 6,
                'languages' => 'English, Igbo',
                'professional_experience' => 'Regional logistics and staff transport.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'driver_id' => 10,
                'supplier_id' => 10,
                'vehicle_id' => 10,
                'driver_name' => 'Samuel Adeoye',
                'phone_number' => '+2348036677885',
                'license_number' => 'LIC-KP1044',
                'years_experience' => 7,
                'languages' => 'English, Yoruba',
                'professional_experience' => 'Airport transfers and corporate bookings.',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
