<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuppliersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('suppliers')->insert([
            [
                'supplier_id' => 1,
                'business_name' => 'Citywide Mobility Ltd',
                'business_type' => 'Transport Services',
                'contact_person' => 'Aisha Bello',
                'phone_number' => '+2348012345678',
                'email' => 'contact@citywidemobility.test',
                'city' => 'Lagos',
                'business_address' => '12 Adeola Odeku St, Victoria Island, Lagos',
                'years_in_business' => 6,
                'instagram_page' => 'citywidemobility',
                'website' => 'https://citywidemobility.test',
                'status' => 'active',
                'supplier_score' => 85,
                'supplier_tier' => 'gold',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 2,
                'business_name' => 'Northside Chauffeurs',
                'business_type' => 'Chauffeur Services',
                'contact_person' => 'Tunde Okoro',
                'phone_number' => '+2348098765432',
                'email' => 'hello@northsidechauffeurs.test',
                'city' => 'Abuja',
                'business_address' => '45 Aminu Kano Cres, Wuse 2, Abuja',
                'years_in_business' => 4,
                'instagram_page' => null,
                'website' => 'https://northsidechauffeurs.test',
                'status' => 'active',
                'supplier_score' => 72,
                'supplier_tier' => 'silver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 3,
                'business_name' => 'Coastal Fleet Partners',
                'business_type' => 'Fleet Leasing',
                'contact_person' => 'Kehinde Olaniyi',
                'phone_number' => '+2348062201133',
                'email' => 'ops@coastalfleet.test',
                'city' => 'Lagos',
                'business_address' => '18 Admiralty Way, Lekki Phase 1, Lagos',
                'years_in_business' => 9,
                'instagram_page' => 'coastalfleet',
                'website' => 'https://coastalfleet.test',
                'status' => 'active',
                'supplier_score' => 90,
                'supplier_tier' => 'platinum',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 4,
                'business_name' => 'Savanna Ride Services',
                'business_type' => 'Transport Services',
                'contact_person' => 'Fatima Yusuf',
                'phone_number' => '+2347051112299',
                'email' => 'info@savannaride.test',
                'city' => 'Kano',
                'business_address' => '7 Zoo Road, Kano',
                'years_in_business' => 5,
                'instagram_page' => null,
                'website' => 'https://savannaride.test',
                'status' => 'active',
                'supplier_score' => 68,
                'supplier_tier' => 'silver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 5,
                'business_name' => 'Riverline Transport Co',
                'business_type' => 'Corporate Transport',
                'contact_person' => 'Bola Akinyemi',
                'phone_number' => '+2348023344556',
                'email' => 'admin@riverline.test',
                'city' => 'Port Harcourt',
                'business_address' => '22 Stadium Rd, Port Harcourt',
                'years_in_business' => 7,
                'instagram_page' => 'riverlinetransport',
                'website' => null,
                'status' => 'active',
                'supplier_score' => 74,
                'supplier_tier' => 'silver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 6,
                'business_name' => 'Metroline Logistics',
                'business_type' => 'Logistics',
                'contact_person' => 'David Umeh',
                'phone_number' => '+2348039901122',
                'email' => 'support@metroline.test',
                'city' => 'Enugu',
                'business_address' => '5 Ogui Rd, Enugu',
                'years_in_business' => 3,
                'instagram_page' => null,
                'website' => 'https://metroline.test',
                'status' => 'active',
                'supplier_score' => 61,
                'supplier_tier' => 'bronze',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 7,
                'business_name' => 'Capital Executive Cars',
                'business_type' => 'Chauffeur Services',
                'contact_person' => 'Zainab Musa',
                'phone_number' => '+2348077711223',
                'email' => 'hello@capitalexec.test',
                'city' => 'Abuja',
                'business_address' => '16 Ademola Adetokunbo Cres, Abuja',
                'years_in_business' => 8,
                'instagram_page' => 'capitalexec',
                'website' => 'https://capitalexec.test',
                'status' => 'active',
                'supplier_score' => 88,
                'supplier_tier' => 'gold',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 8,
                'business_name' => 'Harborlink Mobility',
                'business_type' => 'Transport Services',
                'contact_person' => 'Chidi Nwachukwu',
                'phone_number' => '+2348095544332',
                'email' => 'ops@harborlink.test',
                'city' => 'Warri',
                'business_address' => '33 Airport Rd, Warri',
                'years_in_business' => 2,
                'instagram_page' => null,
                'website' => null,
                'status' => 'active',
                'supplier_score' => 55,
                'supplier_tier' => 'bronze',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 9,
                'business_name' => 'Eastern Route Fleet',
                'business_type' => 'Fleet Leasing',
                'contact_person' => 'Ngozi Okafor',
                'phone_number' => '+2348026677889',
                'email' => 'team@easternroute.test',
                'city' => 'Onitsha',
                'business_address' => '10 New Market Rd, Onitsha',
                'years_in_business' => 10,
                'instagram_page' => 'easternroute',
                'website' => 'https://easternroute.test',
                'status' => 'active',
                'supplier_score' => 92,
                'supplier_tier' => 'platinum',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 10,
                'business_name' => 'Summit Transport Group',
                'business_type' => 'Corporate Transport',
                'contact_person' => 'Emeka Obi',
                'phone_number' => '+2348041122334',
                'email' => 'contact@summittransport.test',
                'city' => 'Ibadan',
                'business_address' => '77 Ring Rd, Ibadan',
                'years_in_business' => 5,
                'instagram_page' => null,
                'website' => 'https://summittransport.test',
                'status' => 'active',
                'supplier_score' => 70,
                'supplier_tier' => 'silver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
