<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiclesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehicles')->insert([
            [
                'vehicle_id' => 1,
                'supplier_id' => 1,
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'Camry',
                'vehicle_year' => 2021,
                'vehicle_color' => 'Black',
                'plate_number' => 'LAG-4523',
                'vehicle_category' => 'sedan',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'excellent',
                'air_condition' => true,
                'vehicle_location' => 'Lagos',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 2,
                'supplier_id' => 2,
                'vehicle_make' => 'Honda',
                'vehicle_model' => 'Accord',
                'vehicle_year' => 2020,
                'vehicle_color' => 'Gray',
                'plate_number' => 'ABJ-3381',
                'vehicle_category' => 'sedan',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'very good',
                'air_condition' => true,
                'vehicle_location' => 'Abuja',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 3,
                'supplier_id' => 3,
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'Hiace',
                'vehicle_year' => 2019,
                'vehicle_color' => 'White',
                'plate_number' => 'LAG-8741',
                'vehicle_category' => 'van',
                'passenger_capacity' => 12,
                'vehicle_condition' => 'good',
                'air_condition' => true,
                'vehicle_location' => 'Lagos',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 4,
                'supplier_id' => 4,
                'vehicle_make' => 'Hyundai',
                'vehicle_model' => 'Sonata',
                'vehicle_year' => 2018,
                'vehicle_color' => 'Silver',
                'plate_number' => 'KAN-5502',
                'vehicle_category' => 'sedan',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'good',
                'air_condition' => true,
                'vehicle_location' => 'Kano',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 5,
                'supplier_id' => 5,
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'Corolla',
                'vehicle_year' => 2022,
                'vehicle_color' => 'Blue',
                'plate_number' => 'PHC-1920',
                'vehicle_category' => 'sedan',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'excellent',
                'air_condition' => true,
                'vehicle_location' => 'Port Harcourt',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 6,
                'supplier_id' => 6,
                'vehicle_make' => 'Kia',
                'vehicle_model' => 'Sportage',
                'vehicle_year' => 2021,
                'vehicle_color' => 'Red',
                'plate_number' => 'ENU-7788',
                'vehicle_category' => 'suv',
                'passenger_capacity' => 5,
                'vehicle_condition' => 'very good',
                'air_condition' => true,
                'vehicle_location' => 'Enugu',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 7,
                'supplier_id' => 7,
                'vehicle_make' => 'Mercedes-Benz',
                'vehicle_model' => 'E-Class',
                'vehicle_year' => 2022,
                'vehicle_color' => 'Black',
                'plate_number' => 'ABJ-9021',
                'vehicle_category' => 'luxury',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'excellent',
                'air_condition' => true,
                'vehicle_location' => 'Abuja',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 8,
                'supplier_id' => 8,
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'Sienna',
                'vehicle_year' => 2020,
                'vehicle_color' => 'White',
                'plate_number' => 'WAR-4012',
                'vehicle_category' => 'van',
                'passenger_capacity' => 7,
                'vehicle_condition' => 'good',
                'air_condition' => true,
                'vehicle_location' => 'Warri',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 9,
                'supplier_id' => 9,
                'vehicle_make' => 'Ford',
                'vehicle_model' => 'Transit',
                'vehicle_year' => 2019,
                'vehicle_color' => 'White',
                'plate_number' => 'ONI-6207',
                'vehicle_category' => 'van',
                'passenger_capacity' => 14,
                'vehicle_condition' => 'good',
                'air_condition' => true,
                'vehicle_location' => 'Onitsha',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vehicle_id' => 10,
                'supplier_id' => 10,
                'vehicle_make' => 'Lexus',
                'vehicle_model' => 'ES 350',
                'vehicle_year' => 2021,
                'vehicle_color' => 'Gray',
                'plate_number' => 'IBA-3344',
                'vehicle_category' => 'sedan',
                'passenger_capacity' => 4,
                'vehicle_condition' => 'excellent',
                'air_condition' => true,
                'vehicle_location' => 'Ibadan',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
